#Question 1
string1="Python is a case sensitive language" #String1
print("<A>THE LENGTH OF STRING IS",len(string1)) #Function to Find LENGTH OF STRING
print("<B>THE REVERSED STRING IS ",string1[-1::-1])
string2=string1[10:26] #STORED a case sensitive IN A NEW STRING
string2.replace("a case sensitive","object oriented") #REPLACED "a case sensitive" WITH "object oriented"
print("<E>THE INDEX OF SUBSTRING a is ",string1.find('a'))
print("<F>THE ORIGINAL STRING AFTER REMOVING WHITESPACES IS",string1.replace(" ",""))
print("\n")
